### ISSUE TITLE
Alarm Panel Will not load after update to HA

### ISSUE THREAD

**Issue by suds32** [akasma74/Hass-Custom-Alarm#102]
Error shown
This component is not working
Check the Home Assistant log for more details.
This integration: v1.12.4
Home Assistant: v0.111.0

Rebooted twice with no change
from error log
Log Details (ERROR)
Logger: homeassistant.components.alarm_control_panel
Source: components/frontend/__init__.py:190 
Integration: Alarm control panel (documentation, issues) 
First occurred: 11:16:28 AM (1 occurrences) 
Last logged: 11:16:28 AM

Error while setting up bwalarm platform for alarm_control_panel
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 178, in _async_setup_platform
    await asyncio.wait_for(asyncio.shield(task), SLOW_SETUP_MAX_WAIT)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 442, in wait_for
    return fut.result()
  File "/config/custom_components/bwalarm/alarm_control_panel.py", line 401, in async_setup_platform
    config={"alarmid": "alarm_control_panel.house"},
  File "/usr/src/homeassistant/homeassistant/components/panel_custom/__init__.py", line 140, in async_register_panel
    require_admin=require_admin,
  File "/usr/src/homeassistant/homeassistant/components/frontend/__init__.py", line 190, in async_register_built_in_panel
    raise ValueError(f"Overwriting panel {panel.frontend_url_path}")
ValueError: Overwriting panel alarm

**Comment by akasma74** [comment]
Is the browser/app you are using to _display_ HA/alarm panel uses admin account or normal user's one?
If the latter, could you try with the admin account?
Also, have you cleared cache of _all_ your browsers/apps accessing HA before reboot?
