### ISSUE TITLE
Error setting up bwalarm, Overwriting panel alarm

### ISSUE THREAD

**Issue by sparkydave1981** [akasma74/Hass-Custom-Alarm#105]
**The component:**
 - Current version: v1.12.6
 - Last known working version (if any): unknown

**Your setup:**
 - Home Assistant version: 0.111.2
 - Last known working Home Assistant version (if any):
 - OS: Ubuntu / HA Supervised on generic linux
 - Browser name & version: Chrome

**Describe the bug**
Error in log as per below, component still seems to function ok.

**To Reproduce**
Error occurs in log after each HA restart.

**Expected behavior**
No error

**Your bwalarm.yaml**
```
platform: bwalarm
name: House
code: 'REDACTED'
panic_code: 'REDACTED'
alarm: automation.alarm_triggered
warning: automation.alarm_warning
mqtt:
  enable_mqtt: true
  payload_arm_home: armed_home
  command_topic: paradoxdCTL/hassio/Arm
  pending_on_warning: false
  qos: 0
  payload_disarm: disarmed
  override_code: true
  state_topic: paradoxdCTL/in
  payload_arm_night: armed_home
  payload_arm_away: armed_away
enable_night_mode: false


enable_persistence: true
passcode_attempts: '3'
passcode_attempts_timeout: '60'
admin_password: REDACTED
panel:
  cameras: []
states:
  armed_away:
    immediate:
    - binary_sensor.gym_multisensor_sensor
    - binary_sensor.motion_sensor_158d0001ad43db
    - binary_sensor.ensuite_multisensor_motion
    - binary_sensor.lounge_multisensor_sensor
    - binary_sensor.kitchen_multi_sensor_sensor
    - binary_sensor.paradox_z14_main_shed_pir
    - binary_sensor.paradox_z1_panel_siren_tampers
    - binary_sensor.paradox_z16_repeater_tamper
    - binary_sensor.paradox_z5_living_pir
    - binary_sensor.paradox_z15_garden_shed_pir
    - binary_sensor.paradox_alarm_triggered
    delayed:
    - binary_sensor.passage_multi_sensor_sensor
    - binary_sensor.paradox_z4_lounge_pir
    override:
    - binary_sensor.passage_multi_sensor_sensor
    pending_time: 30
    warning_time: 60
    trigger_time: 600
  armed_home:
    immediate:
    - binary_sensor.gym_multisensor_sensor
    - binary_sensor.paradox_z14_main_shed_pir
    - binary_sensor.paradox_z15_garden_shed_pir
    - binary_sensor.paradox_z16_repeater_tamper
    - binary_sensor.paradox_z1_panel_siren_tampers
    - binary_sensor.paradox_alarm_triggered
    delayed:
    - binary_sensor.paradox_z6_alfresco_pir
    override: []
    pending_time: 15
    warning_time: 15
    trigger_time: 600
```
```yaml
```
**Home Assistant log**

> 2020-06-15 11:42:10 ERROR (MainThread) [homeassistant.components.alarm_control_panel] Error while setting up bwalarm platform for alarm_control_panel
> Traceback (most recent call last):
> File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 178, in _async_setup_platform
> await asyncio.wait_for(asyncio.shield(task), SLOW_SETUP_MAX_WAIT)
> File "/usr/local/lib/python3.7/asyncio/tasks.py", line 442, in wait_for
> return fut.result()
> File "/config/custom_components/bwalarm/alarm_control_panel.py", line 401, in async_setup_platform
> config={"alarmid": "alarm_control_panel.house"},
> File "/usr/src/homeassistant/homeassistant/components/panel_custom/init.py", line 140, in async_register_panel
> require_admin=require_admin,
> File "/usr/src/homeassistant/homeassistant/components/frontend/init.py", line 190, in async_register_built_in_panel
> raise ValueError(f"Overwriting panel {panel.frontend_url_path}")
> ValueError: Overwriting panel alarm

```txt
```
**Screenshots**

**Additional context**
<!-- Add any other context about the problem here.<!--

**Comment by akasma74** [comment]
Can you do what I asked people to do [here](https://github.com/akasma74/Hass-Custom-Alarm/issues/94#issuecomment-642577208) and update your issue description with the results?

**Comment by sparkydave1981** [comment]
No problem.  Here is the full log using the new .py file

> 2020-06-17 09:04:08 DEBUG (MainThread) [custom_components.bwalarm.alarm_control_panel] [_state_schema]
> 2020-06-17 09:04:08 DEBUG (MainThread) [custom_components.bwalarm.alarm_control_panel] [_state_schema]
> 2020-06-17 09:04:08 DEBUG (MainThread) [custom_components.bwalarm.alarm_control_panel] [_state_schema]
> 2020-06-17 09:04:08 DEBUG (MainThread) [custom_components.bwalarm.alarm_control_panel] [_state_schema]
> 2020-06-17 09:04:08 DEBUG (MainThread) [custom_components.bwalarm.alarm_control_panel] [_state_validator]
> 2020-06-17 09:04:09 DEBUG (MainThread) [custom_components.bwalarm.alarm_control_panel] [async_setup_platform] begin
> 2020-06-17 09:04:09 DEBUG (MainThread) [custom_components.bwalarm.alarm_control_panel] [async_setup_platform] frontend_panels(12): 
> 2020-06-17 09:04:09 DEBUG (MainThread) [custom_components.bwalarm.alarm_control_panel] [async_setup_platform] frontend_panel lovelace: {'component_name': 'lovelace', 'icon': None, 'title': None, 'config': {'mode': 'storage'}, 'url_path': 'lovelace', 'require_admin': False} 
> 2020-06-17 09:04:09 DEBUG (MainThread) [custom_components.bwalarm.alarm_control_panel] [async_setup_platform] frontend_panel config: {'component_name': 'config', 'icon': 'hass:settings', 'title': 'config', 'config': None, 'url_path': 'config', 'require_admin': True} 
> 2020-06-17 09:04:09 DEBUG (MainThread) [custom_components.bwalarm.alarm_control_panel] [async_setup_platform] frontend_panel hassio: {'component_name': 'custom', 'icon': 'hass:home-assistant', 'title': 'Supervisor', 'config': {'_panel_custom': {'name': 'hassio-main', 'embed_iframe': True, 'trust_external': False, 'js_url': '/api/hassio/app/entrypoint.js'}}, 'url_path': 'hassio', 'require_admin': True} 
> 2020-06-17 09:04:09 DEBUG (MainThread) [custom_components.bwalarm.alarm_control_panel] [async_setup_platform] frontend_panel profile: {'component_name': 'profile', 'icon': None, 'title': None, 'config': None, 'url_path': 'profile', 'require_admin': False} 
> 2020-06-17 09:04:09 DEBUG (MainThread) [custom_components.bwalarm.alarm_control_panel] [async_setup_platform] frontend_panel developer-tools: {'component_name': 'developer-tools', 'icon': 'hass:hammer', 'title': 'developer_tools', 'config': None, 'url_path': 'developer-tools', 'require_admin': True} 
> 2020-06-17 09:04:09 DEBUG (MainThread) [custom_components.bwalarm.alarm_control_panel] [async_setup_platform] frontend_panel a0d7b954_grocy: {'component_name': 'custom', 'icon': 'mdi:cart', 'title': 'Grocy', 'config': {'ingress': 'a0d7b954_grocy', '_panel_custom': {'name': 'hassio-main', 'embed_iframe': True, 'trust_external': False, 'js_url': '/api/hassio/app/entrypoint.js'}}, 'url_path': 'a0d7b954_grocy', 'require_admin': True} 
> 2020-06-17 09:04:09 DEBUG (MainThread) [custom_components.bwalarm.alarm_control_panel] [async_setup_platform] frontend_panel 00185a40_simplescheduler: {'component_name': 'custom', 'icon': 'mdi:calendar-clock', 'title': 'Scheduler', 'config': {'ingress': '00185a40_simplescheduler', '_panel_custom': {'name': 'hassio-main', 'embed_iframe': True, 'trust_external': False, 'js_url': '/api/hassio/app/entrypoint.js'}}, 'url_path': '00185a40_simplescheduler', 'require_admin': False} 
> 2020-06-17 09:04:09 DEBUG (MainThread) [custom_components.bwalarm.alarm_control_panel] [async_setup_platform] frontend_panel a0d7b954_vscode: {'component_name': 'custom', 'icon': 'mdi:visual-studio-code', 'title': 'Visual Studio Code', 'config': {'ingress': 'a0d7b954_vscode', '_panel_custom': {'name': 'hassio-main', 'embed_iframe': True, 'trust_external': False, 'js_url': '/api/hassio/app/entrypoint.js'}}, 'url_path': 'a0d7b954_vscode', 'require_admin': True} 
> 2020-06-17 09:04:09 DEBUG (MainThread) [custom_components.bwalarm.alarm_control_panel] [async_setup_platform] frontend_panel 15ef4d2f_esphome: {'component_name': 'custom', 'icon': 'mdi:chip', 'title': 'ESPHome', 'config': {'ingress': '15ef4d2f_esphome', '_panel_custom': {'name': 'hassio-main', 'embed_iframe': True, 'trust_external': False, 'js_url': '/api/hassio/app/entrypoint.js'}}, 'url_path': '15ef4d2f_esphome', 'require_admin': True} 
> 2020-06-17 09:04:09 DEBUG (MainThread) [custom_components.bwalarm.alarm_control_panel] [async_setup_platform] frontend_panel logbook: {'component_name': 'logbook', 'icon': 'hass:format-list-bulleted-type', 'title': 'logbook', 'config': None, 'url_path': 'logbook', 'require_admin': False} 
> 2020-06-17 09:04:09 DEBUG (MainThread) [custom_components.bwalarm.alarm_control_panel] [async_setup_platform] frontend_panel history: {'component_name': 'history', 'icon': 'hass:poll-box', 'title': 'history', 'config': None, 'url_path': 'history', 'require_admin': False} 
> 2020-06-17 09:04:09 DEBUG (MainThread) [custom_components.bwalarm.alarm_control_panel] [async_setup_platform] frontend_panel cctv: {'component_name': 'iframe', 'icon': 'mdi:cctv', 'title': 'CCTV', 'config': {'url': 'https://192.168.0.100'}, 'url_path': 'cctv', 'require_admin': False} 
> 2020-06-17 09:04:09 DEBUG (MainThread) [custom_components.bwalarm.alarm_control_panel] [__init__] begin
> 2020-06-17 09:04:09 DEBUG (MainThread) [custom_components.bwalarm.alarm_control_panel] [init_folders] _hadir: /config
> 2020-06-17 09:04:09 DEBUG (MainThread) [custom_components.bwalarm.alarm_control_panel] [init_folders] integration: _integrationdir: /config/custom_components/bwalarm, _defimagesdir: /config/custom_components/bwalarm/resources/images
> 2020-06-17 09:04:09 DEBUG (MainThread) [custom_components.bwalarm.alarm_control_panel] [init_folders] config: _configdir: /config/resources/bwalarm, _yaml_config: /config/resources/bwalarm/bwalarm.yaml, _json_persistence: /config/resources/bwalarm/bwalarm.json, _json_log: /config/resources/bwalarm/bwalarm_log.json
> 2020-06-17 09:04:09 DEBUG (MainThread) [custom_components.bwalarm.alarm_control_panel] [init_folders] override: _datadir: /config/resources/bwalarm, _imagesdir: /config/resources/bwalarm/images
> 2020-06-17 09:04:09 DEBUG (MainThread) [custom_components.bwalarm.alarm_control_panel] [init_variables] begin
> 2020-06-17 09:04:09 DEBUG (MainThread) [custom_components.bwalarm.alarm_control_panel] [init_variables] states: init armed_away
> 2020-06-17 09:04:09 DEBUG (MainThread) [custom_components.bwalarm.alarm_control_panel] [init_variables] states: init armed_home
> 2020-06-17 09:04:09 DEBUG (MainThread) [custom_components.bwalarm.alarm_control_panel] [init_variables] users present, let's fix picture paths..
> 2020-06-17 09:04:09 DEBUG (MainThread) [custom_components.bwalarm.alarm_control_panel] [_fix_old_style_user_pictures] processing user Hass.io
> 2020-06-17 09:04:09 DEBUG (MainThread) [custom_components.bwalarm.alarm_control_panel] [_fix_old_style_user_pictures] processing user Dave
> 2020-06-17 09:04:09 DEBUG (MainThread) [custom_components.bwalarm.alarm_control_panel] [_fix_old_style_user_pictures] processing user Rowe
> 2020-06-17 09:04:09 DEBUG (MainThread) [custom_components.bwalarm.alarm_control_panel] [_fix_old_style_user_pictures] processing user hassio_mqtt
> 2020-06-17 09:04:09 DEBUG (MainThread) [custom_components.bwalarm.alarm_control_panel] [_fix_old_style_user_pictures] processing user Tablet
> 2020-06-17 09:04:09 DEBUG (MainThread) [custom_components.bwalarm.alarm_control_panel] [_fix_old_style_user_pictures] processing user Home Assistant Cloud
> 2020-06-17 09:04:09 DEBUG (MainThread) [custom_components.bwalarm.alarm_control_panel] [_fix_old_style_user_pictures] processing user Home Assistant Cast
> 2020-06-17 09:04:09 DEBUG (MainThread) [custom_components.bwalarm.alarm_control_panel] [_fix_old_style_user_pictures] processing user House_S7
> 2020-06-17 09:04:09 DEBUG (MainThread) [custom_components.bwalarm.alarm_control_panel] [load_yaml] File "/config/resources/bwalarm/bwalarm.yaml" loaded successfully
> 2020-06-17 09:04:09 DEBUG (MainThread) [custom_components.bwalarm.alarm_control_panel] [clearsignals]
> 2020-06-17 09:04:09 DEBUG (MainThread) [custom_components.bwalarm.alarm_control_panel] [init_variables] end
> 2020-06-17 09:04:09 DEBUG (MainThread) [custom_components.bwalarm.alarm_control_panel] [__init__] end
> 2020-06-17 09:04:09 DEBUG (MainThread) [custom_components.bwalarm.alarm_control_panel] [async_setup_platform] end
> 2020-06-17 09:04:09 ERROR (MainThread) [homeassistant.components.panel_custom] Unable to register panel Alarm: Overwriting panel alarm
> 2020-06-17 09:04:09 DEBUG (MainThread) [custom_components.bwalarm.alarm_control_panel] [async_added_to_hass] begin
> 2020-06-17 09:04:09 DEBUG (MainThread) [custom_components.bwalarm.alarm_control_panel] [async_added_to_hass] mqtt enabled, call async_track_state_change(alarm_control_panel.house)
> 2020-06-17 09:04:09 DEBUG (MainThread) [custom_components.bwalarm.alarm_control_panel] [async_added_to_hass] mqtt enabled, call async_subscribe(alarm_control_panel.house)
> 2020-06-17 09:04:09 DEBUG (MainThread) [custom_components.bwalarm.alarm_control_panel] [async_added_to_hass] end
> 2020-06-17 09:04:09 DEBUG (MainThread) [custom_components.bwalarm.alarm_control_panel] [code_format] self._code: REDACTED, self._state: disarmed, code_arm_required: False - return None
> 2020-06-17 09:04:09 DEBUG (MainThread) [custom_components.bwalarm.alarm_control_panel] [device_state_attributes]
> 2020-06-17 09:04:09 DEBUG (MainThread) [custom_components.bwalarm.alarm_control_panel] [message_received] payload: "disarmed"
> 2020-06-17 09:04:09 DEBUG (MainThread) [custom_components.bwalarm.alarm_control_panel] [message_received] require passcode to disarm option: Disabled
> 2020-06-17 09:04:09 INFO (MainThread) [custom_components.bwalarm.alarm_control_panel] [message_received] DISARMED without passcode (override mode)
> 2020-06-17 09:04:09 DEBUG (SyncWorker_22) [custom_components.bwalarm.alarm_control_panel] [alarm_disarm] passcode: "REDACTED" - begin
> 2020-06-17 09:04:09 DEBUG (SyncWorker_22) [custom_components.bwalarm.alarm_control_panel] [process_event] event: Events.Disarm, state: disarmed, override_pending_time: False - begin
> 2020-06-17 09:04:09 DEBUG (SyncWorker_22) [custom_components.bwalarm.alarm_control_panel] [process_event] event: Events.Disarm, state: disarmed, override_pending_time: False - end
> 2020-06-17 09:04:09 DEBUG (SyncWorker_22) [custom_components.bwalarm.alarm_control_panel] [alarm_disarm] passcode: "REDACTED" - end (return True)
> 2020-06-17 09:04:09 DEBUG (MainThread) [custom_components.bwalarm.alarm_control_panel] [code_format] self._code: REDACTED, self._state: disarmed, code_arm_required: False - return None
> 2020-06-17 09:04:09 DEBUG (MainThread) [custom_components.bwalarm.alarm_control_panel] [device_state_attributes]
> 2020-06-17 09:04:10 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for bom_forecast which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.
> 2020-06-17 09:04:10 DEBUG (MainThread) [custom_components.bwalarm.alarm_control_panel] [message_received] payload: "disarmed"
> 2020-06-17 09:04:10 DEBUG (MainThread) [custom_components.bwalarm.alarm_control_panel] [message_received] require passcode to disarm option: Disabled
> 2020-06-17 09:04:10 INFO (MainThread) [custom_components.bwalarm.alarm_control_panel] [message_received] DISARMED without passcode (override mode)
> 2020-06-17 09:04:10 DEBUG (SyncWorker_10) [custom_components.bwalarm.alarm_control_panel] [alarm_disarm] passcode: "REDACTED" - begin
> 2020-06-17 09:04:10 DEBUG (SyncWorker_10) [custom_components.bwalarm.alarm_control_panel] [process_event] event: Events.Disarm, state: disarmed, override_pending_time: False - begin
> 2020-06-17 09:04:10 DEBUG (SyncWorker_10) [custom_components.bwalarm.alarm_control_panel] [process_event] event: Events.Disarm, state: disarmed, override_pending_time: False - end
> 2020-06-17 09:04:10 DEBUG (SyncWorker_10) [custom_components.bwalarm.alarm_control_panel] [alarm_disarm] passcode: "REDACTED" - end (return True)
> 2020-06-17 09:04:10 DEBUG (MainThread) [custom_components.bwalarm.alarm_control_panel] [code_format] self._code: REDACTED, self._state: disarmed, code_arm_required: False - return None
> 2020-06-17 09:04:10 DEBUG (MainThread) [custom_components.bwalarm.alarm_control_panel] [device_state_attributes]

**Comment by akasma74** [comment]
Any changes in the alarm's behaviour using the new code?
I no longer see an exception in the logs, just an error.

And if the alarm is working, I'd say it's HA issue, namely - they log ERROR when there's no error.
So if it's an annoying error and you have time, you can try opening a new issue with HA core.

**Comment by akasma74** [comment]
@sparkydave1981 any news here?

**Comment by sparkydave1981** [comment]
I don't seem to have any change in the alarm behaviour.  I haven't restarted HA for some days so haven't had repeat log entries (it only logged the error once at startup)

**Comment by riddik14** [comment]
2020-07-14 17:26:19 ERROR (MainThread) [homeassistant.components.alarm_control_panel] Error while setting up bwalarm platform for alarm_control_panel
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 178, in _async_setup_platform
    await asyncio.wait_for(asyncio.shield(task), SLOW_SETUP_MAX_WAIT)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 442, in wait_for
    return fut.result()
  File "/config/custom_components/bwalarm/alarm_control_panel.py", line 401, in async_setup_platform
    config={"alarmid": "alarm_control_panel.house"},
  File "/usr/src/homeassistant/homeassistant/components/panel_custom/__init__.py", line 149, in async_register_panel
    require_admin=require_admin,
  File "/usr/src/homeassistant/homeassistant/components/frontend/__init__.py", line 190, in async_register_built_in_panel
    raise ValueError(f"Overwriting panel {panel.frontend_url_path}")
ValueError: Overwriting panel alarm

**Comment by lancelon** [comment]
@riddik14 or @sparkydave1981 any progress with this? Are you guys up and running again? Tearing my hair out here!

**Comment by akasma74** [comment]
@lancelon I can see you asking for help in different discussions - what's the issue you're experiencing?

**Comment by riddik14** [comment]
I have to remove all, restart and install new all from HACS
