### ISSUE TITLE
0.115 no longer supports html_url for registering panel

### ISSUE THREAD

**Issue by aidbish** [akasma74/Hass-Custom-Alarm#124]
**The component:**
 - Current version: 1.12.6
 - Last known working version (if any):

**Your setup:**
 - Home Assistant version: 0.115b4
 - Last known working Home Assistant version (if any): 0.114
 - OS: ubuntu
 - Browser name & version: chrome, latest

**Describe the bug**
in 0.115 the html_url is no longer valid for regsitering the panel and bwalarm doesnt load

https://github.com/home-assistant/core/pull/39799

**Comment by callahan17** [comment]
Same here, latest version 0.115.0 has breaking changes.
Also don't know if this helps AgentDVR's update also has a new alarm panel alarm_control_panel.nvr_alarm_panel does this conflict?
Logger: homeassistant.components.alarm_control_panel
Source: custom_components/bwalarm/alarm_control_panel.py:395
Integration: Alarm Control Panel (documentation, issues)
First occurred: 7:20:56 (1 occurrences)
Last logged: 7:20:56

Error while setting up bwalarm platform for alarm_control_panel
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 193, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/bwalarm/alarm_control_panel.py", line 395, in async_setup_platform
    await hass.components.panel_custom.async_register_panel(
TypeError: async_register_panel() got an unexpected keyword argument 'html_url'

**Comment by BigHomie90** [comment]
Same here.. The funny thing is that i was on 114 version when i found this integration. I was super excited to test it so i installed it and had a quick look at the web interface etc. At the same time the 0.115 update notification appeared. I did the update and its not working cause they did some breaking changes and i didn't even have 5 minutes to test the integration. xD.

**Comment by ronniebee** [comment]
Same here.... since 1.15 no working alarm anymore. Entity not availability..... please advice...

**Comment by aidbish** [comment]
Either rollback to 0.114  or wait till updated by developer 
https://community.home-assistant.io/t/bwalarm-akasma74-edition/113666/852

**Comment by isabellaalstrom** [comment]
If you are not using the panel, or rather have the alarm working at all without the panel, you can just comment out that line and the integration should work. Without the panel.

**Comment by ronbrou** [comment]
Thank you for he workaround. I comment out the line for the panel and that did the trick for me.

Met vriendelijke groet,

Ron Brouwers

Gsm: +31 653 86 21 04
Mail: ron.brouwers@outlook.com<mailto:ron.brouwers@outlook.com>

**Comment by e2m32** [comment]
FYI, here are the lines that need to be commented out:

`custom_components\bwalarm\alarm_control_panel.py: lines 392 to 402`
    
    # Register the panel
    # url = "/api/panel_custom/alarm"
    # resources = os.path.join(_resources_folder(hass), PANEL_FNAME)
    # hass.http.register_static_path(url, resources)
    # await hass.components.panel_custom.async_register_panel(
        # webcomponent_name='alarm',
        # frontend_url_path="alarm",
        # html_url=url,
        # sidebar_title='Alarm',
        # sidebar_icon='mdi:shield-home',
        # config={"alarmid": "alarm_control_panel.house"},
    # )

**Comment by CancunManny** [comment]
> If you are not using the panel, or rather have the alarm working at all without the panel, you can just comment out that line and the integration should work. Without the panel.

I am having the same problem after one of the recent updates.  Basically the Alarm link on the left column is gone.  I am guessing the section blocked on the code will make the rest of the alarm function properly, like the keypad on the overview screen, but how would we make changes to the alarm setting, like if I get a new motion sensor.

**Comment by ronniebee** [comment]
I got rid of this alarm and made a new one with the panel card and Manual platform. See //manual on the website of HA. Some rework but at least one that is maintained...

**Comment by e2m32** [comment]
You can directly edit the `resources\bwalarm\bwalarm.yaml` file that the web UI produces. This was used originally before the web UI was built out. You probably have to restart HA in order to load changes... I think the UI updates on the click save buttons.

**Comment by marine1988** [comment]
Any news on this matter my home was no alarm now :(

**Comment by akasma74** [comment]
@marine1988 mate, roll back HA to 0.114 until I fix it, that's the only option ATM.
I know you guys want it back but I'm still way too busy and will definitely come back and fix it as soon as I have time.

**Comment by e2m32** [comment]
> Any news on this matter my home was no alarm now :(

@marine1988, you can either do what @akasma74 suggested and downgrade or you can upgrade to the latest version of this alarm and install the [lovelace alarm panel](https://www.home-assistant.io/lovelace/alarm-panel/). It's super simple to setup, it takes like 2 clicks if your using the UI based (default) version of lovelace. It works great with this custom component, I've used it this way before @akasma74 graciously forked and took ownership of this project and still use it this way.

**Comment by akasma74** [comment]
Yes, some people use the standard LL alarm card to control this alarm.
There are some limitations though, namely:
- one cannot change settings from GUI
- if there are open sensors, your alarm won't arm and the card won't tell you anything
- no coundown etc

**Comment by jes1417** [comment]
@akasma74 and it's too small on a 7" display...

**Comment by akasma74** [comment]
Well, I think size is fixable using card-mod.. but it's additional work.
This integration can automatically scale its content so it takes up whole panel.

**Comment by e2m32** [comment]
The alarm will still arm if there are open sensors, but your right on the other points. Not saying that it's a fix, but it's a work around in the mean time if you need to be on HA 0.115+

**Comment by marine1988** [comment]
> The alarm will still arm if there are open sensors, but your right on the other points. Not saying that it's a fix, but it's a work around in the mean time if you need to be on HA 0.115+

yes me too sdlay I cant use this alarm anymore :( is there any ETA @akasma74 for the fix?

**Comment by akasma74** [comment]
> The alarm will still arm if there are open sensors

Only if __ignore_open_sensors__ is set to __true__.

> yes me too sadlay I cant use this alarm anymore

I don't quite unedrstand.. you have options for both pre 0.115 and 0.115+ so why exactly can't you use the alarm anymore?

> is there any ETA @akasma74 for the fix?

I don't want to give false promises mate.. at least because a) I'm still working every day to complete my offline project and b) it's not a simple fix - it most likely will require for me to learn how to create custom Lovelace cards, not a quick task.

So as I previously said - stay tuned, I'll come back to it as soon as I can.

**Comment by akasma74** [comment]
I think it's too early to close this issue ;)
