### ISSUE TITLE
New issue on core-2022.5.0b1

### ISSUE THREAD

**Issue by jes1417** [akasma74/Hass-Custom-Alarm#139]
**The component:**
 - Current version: v.1.12.13
 - Last known working version (if any):

**Your setup:**
 - Home Assistant version: core-2022.5.0b1
 - Last known working Home Assistant version (if any): core-2022.4.7
 - OS: Docker
 - Browser name & version: Chrome 100.0.4896.127

**Describe the bug**

New error in the log after update
**To Reproduce**

**Expected behavior**

**Your bwalarm.yaml**

```yaml
```
**Home Assistant log**

```This error originated from a custom integration.

Logger: homeassistant.config
Source: custom_components/bwalarm/alarm_control_panel.py:31
Integration: bwalarm (documentation)
First occurred: 3:18:11 PM (1 occurrences)
Last logged: 3:18:11 PM

Platform error: alarm_control_panel
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config.py", line 877, in async_process_component_config
    platform = p_integration.get_platform(domain)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 603, in get_platform
    cache[full_name] = self._import_platform(platform_name)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 620, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/config/custom_components/bwalarm/alarm_control_panel.py", line 31, in <module>
    from homeassistant.const         import (
ImportError: cannot import name 'EVENT_TIME_CHANGED' from 'homeassistant.const' (/usr/src/homeassistant/homeassistant/const.py)

```
**Screenshots**

**Additional context**
<!-- Add any other context about the problem here.<!--

**Comment by jes1417** [comment]
Fixed, thank you!
