### ISSUE TITLE
The integration doesn't start with default config

### ISSUE THREAD

**Issue by mclaudiopt** [akasma74/Hass-Custom-Alarm#16]
hello
i get this error on the log
```
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 126, in _async_setup_platform
    SLOW_SETUP_MAX_WAIT)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 416, in wait_for
    return fut.result()
  File "/config/custom_components/bwalarm/alarm_control_panel.py", line 410, in async_setup_platform
    alarm = BWAlarm(hass, config, mqtt)
  File "/config/custom_components/bwalarm/alarm_control_panel.py", line 431, in __init__
    self.init_variables()
  File "/config/custom_components/bwalarm/alarm_control_panel.py", line 570, in init_variables
    arm_states_dict = self._config[CONF_STATES]
KeyError: 'states'

```
what can i do?
thanks

**Comment by akasma74** [comment]
Can you edit your issue to make it a proper one?
Otherwise I won't be able to help you as I can't see THAT far..

**Comment by johntdyer** [comment]
FWIW I am also running into this

Installed via HAC's

Version. 1.4
Hass version 0.95.0b1

I think its my config but I am not seeing it yet..

```yaml

platform: bwalarm
name: House
code: '0711'
panic_code: '1170'
warning: automation.alarm_warning
alarm: automation.alarm_triggered
armed_away:
  pending_time: 25

armed_home:
  pending_time: 10
```

**Comment by akasma74** [comment]
I don't know what "Installed via HAC's" is, it will be supported in the next HACS release and so far it is NOT the way to update as per this [discussion](https://community.home-assistant.io/t/bwalarm-akasma74-edition/113666/173).

I also don't get the bit after version info - is that another issue?

Anyway, I'd recommend to download the latest release and try it out (but read the release notes first).

**Comment by mclaudiopt** [comment]
hi. i manually updated, not via HAC but the error is not solvable

This component is not working!
Error while setting up platform bwalarm
(custom_components/bwalarm/alarm_control_panel.py)
Check the Home Assistant log for more details.
Home Assistant: v0.94.4

This Panel: v1.3.8_ak74

log:
```
2019-06-23 21:35:37 WARNING (MainThread) [custom_components.bwalarm.alarm_control_panel] [LOAD_YAML] Error loading file "/config/alarm.yaml": [Errno 2] No such file or directory: '/config/alarm.yaml'
2019-06-23 21:35:39 ERROR (MainThread) [homeassistant.components.alarm_control_panel] Error while setting up platform bwalarm
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 126, in _async_setup_platform
    SLOW_SETUP_MAX_WAIT)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 416, in wait_for
    return fut.result()
  File "/config/custom_components/bwalarm/alarm_control_panel.py", line 410, in async_setup_platform
    alarm = BWAlarm(hass, config, mqtt)
  File "/config/custom_components/bwalarm/alarm_control_panel.py", line 431, in __init__
    self.init_variables()
  File "/config/custom_components/bwalarm/alarm_control_panel.py", line 570, in init_variables
    arm_states_dict = self._config[CONF_STATES]
KeyError: 'states'

```

**Comment by akasma74** [comment]
try to download this [file](https://github.com/akasma74/Hass-Custom-Alarm/blob/dev/custom_components/bwalarm/alarm_control_panel.py) and save it into /config/custom_components/bwalarm folder

**Comment by mclaudiopt** [comment]
now the error is different:
2019-06-24 10:53:50 WARNING (MainThread) [custom_components.bwalarm.alarm_control_panel] [LOAD_YAML] Error loading file "/config/alarm.yaml": [Errno 2] No such file or directory: '/config/alarm.yaml'

**Comment by akasma74** [comment]
do you have that alarm.yaml file in your /config folder at all?

**Comment by mclaudiopt** [comment]
now i have and have this
```
Invalid config for [alarm_control_panel]: expected a dictionary. Got OrderedDict([('sun', OrderedDict([('monitored_conditions', ['elevation', 'sunrise', 'sunset', 'max_elevation', 'daylight']), ('scan_interval', OrderedDict([('minutes', 10)]))])), ('script', {}), ('plant', OrderedDict([('planta', OrderedDict([('sensors', OrderedDict([('moisture', 'sensor.planta_moisture'), ('battery', 'sensor.planta_battery'), ('temperature', 'sensor.planta_temperature'), ('conductivity', 'sensor.planta_conductivity'), ('brightness', 'sensor.planta_light_intensity')])), ('min_.... (See ?, line ?). Please check the docs at https://home-assistant.io/components/alarm_control_panel/
```

**Comment by akasma74** [comment]
that's because you need to save this [file](https://github.com/akasma74/Hass-Custom-Alarm/blob/master/alarm.yaml) to your /config folder as alarm.yaml.
currently your configuration.yaml is named alarm.yaml, not the right way to go.

I'd strongly recommen reading [this](https://github.com/akasma74/Hass-Custom-Alarm/blob/master/README.md) and [this](https://github.com/akasma74/Hass-Custom-Alarm/releases/tag/v1.6.0b) before proceeding.

**Comment by mclaudiopt** [comment]
working !
thanks

**Comment by akasma74** [comment]
Looks like the issue is resolved.
