### ISSUE TITLE
error: Platform not found: alarm_control_panel.bwalarm

### ISSUE THREAD

**Issue by superharaldsson** [akasma74/Hass-Custom-Alarm#45]
**Your components (from Alarm/Settings/About):**
 - component version  v1.10.1 from HACS

**Platform & Browser:**
 - Platform name hass.io 0.95.4.
 All browsers

**Describe the bug**
 error: Platform not found: alarm_control_panel.bwalarm
when I update to 0.97.1, Hassio

**Expected behavior**
Tips and solutions

**Screenshots**

**Additional context**

**Comment by akasma74** [comment]
Does that error message come from HA log?
If not, could you post HA log here.
And do I get it that it's not a new installation of this integration but the issue happens after HA update?

**Comment by superharaldsson** [comment]
Log:
2019-08-12 08:43:42 ERROR (MainThread) [homeassistant.config] Failed to get platform alarm_control_panel.bwalarm Traceback (most recent call last): File "/usr/src/homeassistant/homeassistant/config.py", line 795, in async_process_component_config platform = p_integration.get_platform(domain) File "/usr/src/homeassistant/homeassistant/loader.py", line 235, in get_platform "{}.{}".format(self.pkg_path, platform_name) File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module return _bootstrap._gcd_import(name[level:], package, level) File "<frozen importlib._bootstrap>", line 1006, in _gcd_import File "<frozen importlib._bootstrap>", line 983, in _find_and_load File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed File "<frozen importlib._bootstrap>", line 1006, in _gcd_import File "<frozen importlib._bootstrap>", line 983, in _find_and_load File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed File "<frozen importlib._bootstrap>", line 1006, in _gcd_import File "<frozen importlib._bootstrap>", line 983, in _find_and_load File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked ModuleNotFoundError: No module named 'custom_components.'


Yes, no problems before update HA

**Comment by superharaldsson** [comment]
And this error if I disable and enable bwalarm

2019-08-12 09:57:13 ERROR (MainThread) [homeassistant.core] Error executing service <ServiceCall homeassistant.restart (c:3fad73e7432f405fa6cb3504689847ed)>
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/core.py", line 1243, in _safe_execute
    await self._execute_service(handler, service_call)
  File "/usr/src/homeassistant/homeassistant/core.py", line 1260, in _execute_service
    await handler.func(service_call)
  File "/usr/src/homeassistant/homeassistant/components/hassio/__init__.py", line 265, in async_handle_core_service
    errors = await conf_util.async_check_ha_config_file(hass)
  File "/usr/src/homeassistant/homeassistant/config.py", line 835, in async_check_ha_config_file
    res = await check_config.async_check_ha_config_file(hass)
  File "/usr/src/homeassistant/homeassistant/helpers/check_config.py", line 176, in async_check_ha_config_file
    hass, p_integration.domain, p_integration.requirements
  File "/usr/src/homeassistant/homeassistant/requirements.py", line 36, in async_process_requirements
    ret = await hass.async_add_executor_job(_install, hass, req, kwargs)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/requirements.py", line 56, in _install
    progress_path.unlink()
  File "/usr/local/lib/python3.7/pathlib.py", line 1294, in unlink
    self._accessor.unlink(self)
FileNotFoundError: [Errno 2] No such file or directory: '/config/.pip_progress'
2019-08-12 09:58:01 ERROR (MainThread) [homeassistant.components.hassio] Platform not found: alarm_control_panel.bwalarm

**Comment by akasma74** [comment]
> this error if I disable and enable bwalarm

what do you mean and how do you do that?

> Yes, no problems before update HA

so it's something to do with HA then, not sure I can do anything with it..

**Comment by superharaldsson** [comment]
I delete include from configuration.yaml.
Ok! :(

**Comment by akasma74** [comment]
> I delete include from configuration.yaml.

that means 'disable'?
the thing is you provided one log for enabled and disabled, but there should be two or I'm missing something?

**Comment by superharaldsson** [comment]
Exactly. Sorry for my bad English

**Comment by akasma74** [comment]
no worries at all.
It it correct that the first HA log is when you have bwalarm in your configuration.yaml and the second one when you don't?

**Comment by akasma74** [comment]
I'm still waiting for information from you.

**Comment by akasma74** [comment]
I'm closing this issue due to no response from OP.
Feel free to open a new one.
