### ISSUE TITLE
Error arming via manual button after first arm

### ISSUE THREAD

**Issue by necromn** [akasma74/Hass-Custom-Alarm#50]
**Your components (from Alarm/Settings/About):**

This integration: v1.10.2
Home Assistant: v0.98.1
Python: v(3,7,4,final,0)
Running on HassIO and HACS

**Platform & Browser:**
Happens in the iOS App Beta and web clients (chrome and safari) most recent versions

**Describe the bug**
The first arm after restart seems to work ok. But after that neither the core arm button or the panel one work.

2019-08-31 14:21:55 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection.140361486312528] Cannot be called from within the event loop
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 130, in handle_call_service
    connection.context(msg),
  File "/usr/src/homeassistant/homeassistant/core.py", line 1235, in async_call
    await asyncio.shield(self._execute_service(handler, service_call))
  File "/usr/src/homeassistant/homeassistant/core.py", line 1258, in _execute_service
    handler.func(service_call)
  File "/config/custom_components/bwalarm/alarm_control_panel.py", line 423, in alarm_arm_away_from_panel
    alarm.alarm_arm_away_from_panel(service.data.get(ATTR_CODE))
  File "/config/custom_components/bwalarm/alarm_control_panel.py", line 1186, in alarm_arm_away_from_panel
    return self.alarm_arm(Events.ArmAway, code, True)
  File "/config/custom_components/bwalarm/alarm_control_panel.py", line 1161, in alarm_arm
    self.process_event(event, arm_immediately)
  File "/config/custom_components/bwalarm/alarm_control_panel.py", line 1331, in process_event
    self._hass.services.call(self._config.get(CONF_WARNING).split('.')[0], 'turn_on', {'entity_id':self._config.get(CONF_WARNING)})
  File "/usr/src/homeassistant/homeassistant/core.py", line 1173, in call
    self._hass.loop,
  File "/usr/src/homeassistant/homeassistant/util/async_.py", line 151, in run_coroutine_threadsafe
    raise RuntimeError("Cannot be called from within the event loop")
RuntimeError: Cannot be called from within the event loop

Seem to be able to arm via MQTT though

**To Reproduce**
1. Go to alarm sidebar
2. Tap Arm Away

**Expected behavior**
Alarm to arm

**Screenshots**
N/A

**Additional context**
Comes good again when I restart but then stops working again.

**Comment by akasma74** [comment]
Sorry, I don't quite get it.

The **To Reproduce** section is too short, could you edit your post and describe the proper sequence (as your one describes a normal operation and it definitely works).
Also, any information on when it broke? Have you ever had it working?

**Comment by necromn** [comment]
Just upgraded to 99.2 and have some better logs now:

2019-09-23 08:07:30 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection.139674873107792] Cannot be called from within the event loop
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 130, in handle_call_service
    connection.context(msg),
  File "/usr/src/homeassistant/homeassistant/core.py", line 1234, in async_call
    await asyncio.shield(self._execute_service(handler, service_call))
  File "/usr/src/homeassistant/homeassistant/core.py", line 1257, in _execute_service
    handler.func(service_call)
  File "/config/custom_components/bwalarm/alarm_control_panel.py", line 423, in alarm_arm_away_from_panel
    alarm.alarm_arm_away_from_panel(service.data.get(ATTR_CODE))
  File "/config/custom_components/bwalarm/alarm_control_panel.py", line 1186, in alarm_arm_away_from_panel
    return self.alarm_arm(Events.ArmAway, code, True)
  File "/config/custom_components/bwalarm/alarm_control_panel.py", line 1161, in alarm_arm
    self.process_event(event, arm_immediately)
  File "/config/custom_components/bwalarm/alarm_control_panel.py", line 1331, in process_event
    self._hass.services.call(self._config.get(CONF_WARNING).split('.')[0], 'turn_on', {'entity_id':self._config.get(CONF_WARNING)})
  File "/usr/src/homeassistant/homeassistant/core.py", line 1172, in call
    self._hass.loop,
  File "/usr/src/homeassistant/homeassistant/util/async_.py", line 151, in run_coroutine_threadsafe
    raise RuntimeError("Cannot be called from within the event loop")
RuntimeError: Cannot be called from within the event loop

**Comment by necromn** [comment]
This seems to have gone away with HASS 100+
