### ISSUE TITLE
Error setting up platform after upgrade to 0.103.5

### ISSUE THREAD

**Issue by kmycek** [akasma74/Hass-Custom-Alarm#67]
I received the following error in my log after upgrading to 0.103.5

`Error while setting up platform bwalarm
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 150, in _async_setup_platform
    await asyncio.wait_for(asyncio.shield(task), SLOW_SETUP_MAX_WAIT)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 442, in wait_for
    return fut.result()
  File "/config/custom_components/bwalarm/alarm_control_panel.py", line 425, in async_setup_platform
    alarm = BWAlarm(hass, config, mqtt)
TypeError: Can't instantiate abstract class BWAlarm with abstract methods supported_features`

**Comment by akasma74** [comment]
Please read carefully and follow the requirements when opening a new issue.
Your issue has most likely being resolved already, you just don't have the latest version of this integration installed. Check [this](https://github.com/akasma74/Hass-Custom-Alarm/issues/60) out.

By the way, before opening another issue check [that](https://github.com/akasma74/Hass-Custom-Alarm/issues/63) out, too.
