### ISSUE TITLE
Error in logs

### ISSUE THREAD

**Issue by jes1417** [akasma74/Hass-Custom-Alarm#73]
**Your components (from Alarm/Settings/About):**
 - component version v1.11.2pre1

**Platform & Browser:**
 - Platform name & Home assistant version: Docker in OpenMediaVault 5 (Debian) HASS: v0.104.3
 - Browser name & version: Chrome Version 79.0.3945.130 (Official Build) (64-bit) (latest)

**Describe the bug**
A clear and concise description of what the bug is:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_protocol.py", line 461, in start
    await prepare_meth(request)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_fileresponse.py", line 340, in prepare
    fobj = await loop.run_in_executor(None, filepath.open, 'rb')
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.7/pathlib.py", line 1203, in open
    opener=self._opener)
IsADirectoryError: [Errno 21] Is a directory: '/config/resources/bwalarm/images'
```

**To Reproduce**
1. appears in logs on HASS restart

**Comment by akasma74** [comment]
I'm closing it because of no answer. Feel free to open a new one if there's still a problem.
