### ISSUE TITLE
error in logs

### ISSUE THREAD

**Issue by jes1417** [akasma74/Hass-Custom-Alarm#79]
**Your components (from Alarm/Settings/About):**
```
Your Versions:
This integration: v1.11.2pre1

Home Assistant: v0.104.3

Python: v(3,7,6,final,0)
```

**Platform & Browser:**

```
arch | x86_64
-- | --
dev | false
docker | true
hassio | false
os_name | Linux
python_version | 3.7.6
timezone | America/Chicago
version | 0.104.3
virtualenv | false
```

**Describe the bug**
I see this error on startup, not sure where it is coming from here is the debug log.

**Additional context**
```
2020-02-03 13:13:34 DEBUG (MainThread) [hacs.template] 'states' is undefined
2020-02-03 13:13:34 DEBUG (MainThread) [homeassistant.components.websocket_api.http.connection.140685353582800] Received {'type': 'config/auth/list', 'id': 21}
2020-02-03 13:13:34 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection.140685353582800] Error handling message: Unauthorized
2020-02-03 13:13:34 DEBUG (MainThread) [homeassistant.components.websocket_api.http.connection.140685353582800] Sending {'id': 21, 'type': 'result', 'success': False, 'error': {'code': 'unauthorized', 'message': 'Unauthorized'}}
2020-02-03 13:13:34 DEBUG (MainThread) [homeassistant.components.http.view] Serving /bwalarm/images/james.jpg to 192.168.10.59 (auth: False)
2020-02-03 13:13:34 DEBUG (MainThread) [homeassistant.components.http.view] Serving /bwalarm/images/ha.png to 192.168.10.59 (auth: False)
2020-02-03 13:13:34 DEBUG (MainThread) [homeassistant.components.http.view] Serving /bwalarm/images/ha.png to 192.168.10.59 (auth: False)
2020-02-03 13:13:34 DEBUG (MainThread) [homeassistant.components.http.view] Serving /bwalarm/images/dv.jpg to 192.168.10.59 (auth: False)
2020-02-03 13:13:35 DEBUG (SyncWorker_2) [netdisco.ssdp] Found malformed XML at http://172.18.0.3:8080/upnp: <!doctype html><html lang="en"><head><title>HTTP Status 404 – Not Found</title><style type="text/css">h1 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:22px;} h2 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:16px;} h3 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:14px;} body {font-family:Tahoma,Arial,sans-serif;color:black;background-color:white;} b {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;} p {font-family:Tahoma,Arial,sans-serif;background:white;color:black;font-size:12px;} a {color:black;} a.name {color:black;} .line {height:1px;background-color:#525D76;border:none;}</style></head><body><h1>HTTP Status 404 – Not Found</h1></body></html>
2020-02-03 13:13:36 DEBUG (MainThread) [homeassistant.components.http.view] Serving /api/camera_proxy/camera.door to 192.168.10.59 (auth: False)
2020-02-03 13:13:36 DEBUG (MainThread) [homeassistant.components.http.view] Serving /api/camera_proxy/camera.office to 192.168.10.59 (auth: False)
2020-02-03 13:13:36 DEBUG (MainThread) [homeassistant.components.http.view] Serving /api/camera_proxy/camera.dock to 192.168.10.59 (auth: False)
2020-02-03 13:13:37 DEBUG (MainThread) [homeassistant.components.http.view] Serving /bwalarm/images/james.jpg to 192.168.10.59 (auth: False)
2020-02-03 13:13:37 DEBUG (MainThread) [homeassistant.components.http.view] Serving /api/camera_proxy/camera.warehouse to 192.168.10.59 (auth: False)
2020-02-03 13:13:37 DEBUG (MainThread) [homeassistant.components.http.view] Serving /bwalarm/images/ to 192.168.10.59 (auth: False)
2020-02-03 13:13:37 DEBUG (MainThread) [homeassistant.components.http.view] Serving /bwalarm/images/dv.jpg to 192.168.10.59 (auth: False)
2020-02-03 13:13:37 ERROR (MainThread) [aiohttp.server] Unhandled exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_protocol.py", line 461, in start
    await prepare_meth(request)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_fileresponse.py", line 340, in prepare
    fobj = await loop.run_in_executor(None, filepath.open, 'rb')
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.7/pathlib.py", line 1203, in open
    opener=self._opener)
IsADirectoryError: [Errno 21] Is a directory: '/config/resources/bwalarm/images'
2020-02-03 13:13:37 DEBUG (MainThread) [homeassistant.components.http.view] Serving /bwalarm/images/ha.png to 192.168.10.59 (auth: False)
2020-02-03 13:13:39 DEBUG (SyncWorker_17) [homeassistant.components.samsungtv] Try config: {'name': 'HomeAssistant', 'description': 'Samsung 82', 'id': 'ha.component.samsung', 'method': 'websocket', 'port': None, 'host': '192.168.10.34', 'timeout': 1}
2020-02-03 13:13:39 DEBUG (MainThread) [homeassistant.components.http.view] Serving /api/camera_proxy/camera.door to 192.168.10.59 (auth: False)
2020-02-03 13:13:39 DEBUG (MainThread) [homeassistant.components.http.view] Serving /api/camera_proxy/camera.office to 192.168.10.59 (auth: False)
2020-02-03 13:13:39 DEBUG (MainThread) [homeassistant.components.http.view] Serving /api/camera_proxy/camera.dock to 192.168.10.59 (auth: False)
2020-02-03 13:13:39 DEBUG (MainThread) [homeassistant.components.http.view] Serving /api/camera_proxy/camera.warehouse to 192.168.10.59 (auth: False)
```

**Comment by akasma74** [comment]
any other problems with this component or just that error?
was it always like this or started to appear after the component/HA update?

**Comment by jes1417** [comment]
I figured this one out, I had users that did not have an image set, I guess the default is the ha.png and I somehow deleted that file from the user. HA was saying the blank line for the user image was a directory which I guess was technically correct, I added the ha.png and restarted and the error went away. 😁

**Comment by akasma74** [comment]
> I had users that did not have an image set

could you post here a part of your `bwalarm.yaml` describing one of these users?
