### ISSUE TITLE
Integration not working in hass 0.107.0

### ISSUE THREAD

**Issue by isabellaalstrom** [akasma74/Hass-Custom-Alarm#83]
**Your components (from Alarm/Settings/About):**
 - v1.12.1

**Platform & Browser:**
 - Home Assistant (hassio) with Home assistant core 0.107.0

**Describe the bug**
The integration isn't loading at all.

**To Reproduce**
Update Home assistant core to 0.107.0.

**Expected behavior**
The integration should work :)

**LOGS**
```
2020-03-18 19:52:55 ERROR (MainThread) [homeassistant.components.alarm_control_panel] Error while setting up bwalarm platform for alarm_control_panel
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 179, in _async_setup_platform
    await asyncio.wait_for(asyncio.shield(task), SLOW_SETUP_MAX_WAIT)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 442, in wait_for
    return fut.result()
  File "/config/custom_components/bwalarm/alarm_control_panel.py", line 399, in async_setup_platform
    config={"alarmid": "alarm_control_panel.house"},
  File "/usr/src/homeassistant/homeassistant/components/panel_custom/__init__.py", line 140, in async_register_panel
    require_admin=require_admin,
  File "/usr/src/homeassistant/homeassistant/components/frontend/__init__.py", line 190, in async_register_built_in_panel
    raise ValueError(f"Overwriting panel {panel.frontend_url_path}")
ValueError: Overwriting panel alarm
```

**Comment by isabellaalstrom** [comment]
#84 fixes it
